### PR TITLE
Refactor ChEBIOverXPartial 

### PR DESCRIPTION
**Pull request by aditya0by0**
- ### Issue: #50

### CODE REVIEW

**Comment by aditya0by0** [comment]
I tried running `ChEBIOver50Partial`, an implementation of `ChEBIOverXPartial`, with the following data configuration:

```yaml
class_path: chebai.preprocessing.datasets.chebi.ChEBIOver50Partial
init_args:
  top_class_id: 70815
```

And the following run configuration:

```bash
fit
--trainer=configs/training/default_trainer.yml
--model=configs/model/electra.yml
--model.train_metrics=configs/metrics/micro-macro-f1.yml
--model.test_metrics=configs/metrics/micro-macro-f1.yml
--model.val_metrics=configs/metrics/micro-macro-f1.yml
--model.pretrained_checkpoint=G:/github-aditya0by0/electra_pretrained.ckpt
--model.load_prefix=generator.
--data=configs/data/chebi50_partial.yml
--model.out_dim=1511
--model.criterion=configs/loss/bce.yml
--data.init_args.batch_size=10
--trainer.logger.init_args.name=chebi50_bce_unweighted
--data.init_args.num_workers=9
--model.pass_loss_kwargs=false
--data.init_args.chebi_version=231
--data.init_args.chebi_version_train=200
--data.init_args.data_limit=100
```

However, I encountered the following error:

```
 ....
 ....
    self._generate_dynamic_splits()
  File "G:\github-aditya0by0\python-chebai\chebai\preprocessing\datasets\base.py", line 874, in _generate_dynamic_splits
    df_train, df_val, df_test = self._get_data_splits()
  File "G:\github-aditya0by0\python-chebai\chebai\preprocessing\datasets\chebi.py", line 408, in _get_data_splits
    train_df_chebi_ver, df_test_chebi_ver = self.get_test_split(
  File "G:\github-aditya0by0\python-chebai\chebai\preprocessing\datasets\base.py", line 936, in get_test_split
    train_indices, test_indices = next(msss.split(labels_list, labels_list))
  File "G:\anaconda3\envs\env_chebai\lib\site-packages\sklearn\model_selection\_split.py", line 1843, in split
    for train, test in self._iter_indices(X, y, groups):
  File "G:\anaconda3\envs\env_chebai\lib\site-packages\iterstrat\ml_stratifiers.py", line 332, in _iter_indices
    raise ValueError(
ValueError: Supported target type is: multilabel-indicator. Got 'binary' instead.
```

This issue occurs because we are using binary labels in the `labels_list` to indicate whether an instance is a descendant of the top class ID. However, the `MultilabelStratifiedShuffleSplit` expects the target labels to be in a multilabel format (multilabel-indicator).

**Comment by sfluegel05** [comment]
As far as I'm aware, this happens if we don't provide more than 1 label for a multilabel classification task. Since you have chosen a `top_class_id` where the resulting dataset has only 1 class surpassing the 50 SMILES threshold, the dataset only has 1 label. The split function does not like that.
The fix would be to check before the split if the number of labels if >1 and if not, to split the data with some other function.

**Comment by aditya0by0** [comment]
I have implemented the suggested change. Please review.


> As far as I'm aware, this happens if we don't provide more than 1 label for a multilabel classification task. Since you have chosen a `top_class_id` where the resulting dataset has only 1 class surpassing the 50 SMILES threshold, the dataset only has 1 label. The split function does not like that. The fix would be to check before the split if the number of labels if >1 and if not, to split the data with some other function.

**Review by sfluegel05 — APPROVED** [review]
Now it works for me.

However, using 1 label breaks our default metrics (torchmetrics multilabel metrics require >=2 labels -> can be easily solved by using different metrics) and callbacks (which depend on the metrics. This can be avoided by using a different configuration

**Pull request merged**
